server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: http://localhost:8085
          predicates:
            - Path=/auth/**
        - id: STUDENT-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/student/**
        - id: COURSE-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/course/**
        - id: ENROLLMENT-SERVICE
          uri: http://localhost:8083
          predicates:
            - Path=/enrollment/**
        - id: ATTENDANCE-SERVICE
          uri: http://localhost:8084
          predicates:
            - Path=/attendance/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
